export const DEFAULT_THEMES = {

    lightTheme: {
        "close-button-color": "#666666",
        "secondary-button-disabled-opacity": "1",
        "secondary-button-hover-shadow": "0px 4px 10px rgba(0, 0, 0, 0.25)",
        "primary-button-disabled-opacity": "1",
        "primary-button-hover-border": "none",
        "primary-button-disabled-border": "none",
        "primary-button-hover-shadow": "0px 4px 10px rgba(0, 0, 0, 0.25)",
        "banner-background-color": "#F2F2F2",
        "dialog-background-color": "#FFFFFF",
        "primary-button-color": "#0067B8",
        "text-color": "#000000",
        "secondary-button-color": "#EBEBEB",
        "secondary-button-disabled-color": "rgba(0, 0, 0, 0.2)",
        "secondary-button-border": "2px solid #0067B8",
        "background-color-between-page-and-dialog": "rgba(255, 255, 255, 0.6)",
        "dialog-border-color": "#0067B8",
        "hyperlink-font-color": "#0067B8",
        "secondary-button-hover-color": "#DBDBDB",
        "secondary-button-hover-border": "2px solid #0067B8",
        "secondary-button-disabled-border": "none",
        "secondary-button-focus-border-color": "#000000",
        "secondary-button-text-color": "#0067B8",
        "secondary-button-disabled-text-color": "rgba(0, 0, 0, 0.2)",
        "primary-button-hover-color": "#0067B8",
        "primary-button-disabled-color": "rgba(0, 120, 215, 0.2)",
        "primary-button-border": "none",
        "primary-button-focus-border-color": "#000000",
        "primary-button-text-color": "#FFFFFF",
        "primary-button-disabled-text-color": "rgba(0, 0, 0, 0.2)",
        "radio-button-border-color": "#000000",
        "radio-button-checked-background-color": "#000000",
        "radio-button-hover-border-color": "#0067B8",
        "radio-button-hover-background-color": "rgba(0, 0, 0, 0.8)",
        "radio-button-disabled-color": "rgba(0, 0, 0, 0.2)",
        "radio-button-disabled-border-color": "rgba(0, 0, 0, 0.2)",
        "banner-close-button-color": "#000000"
    },

    darkTheme: {
        "close-button-color": "#E3E3E3",
        "secondary-button-disabled-opacity": "0.5",
        "secondary-button-hover-shadow": "none",
        "primary-button-disabled-opacity": "0.5",
        "primary-button-hover-border": "1px solid rgba(0, 0, 0, 0)",
        "primary-button-disabled-border": "1px solid rgba(255, 255, 255, 0)",
        "primary-button-hover-shadow": "none",
        "banner-background-color": "#242424",
        "dialog-background-color": "#171717",
        "primary-button-color": "#4DB2FF",
        "text-color": "#E3E3E3",
        "secondary-button-color": "#171717",
        "secondary-button-disabled-color": "#2E2E2E",
        "secondary-button-border": "1px solid #C7C7C7",
        "background-color-between-page-and-dialog": "rgba(23, 23, 23, 0.6)",
        "dialog-border-color": "#4DB2FF",
        "hyperlink-font-color": "#4DB2FF",
        "secondary-button-hover-color": "#2E2E2E",
        "secondary-button-hover-border": "1px solid #C7C7C7",
        "secondary-button-disabled-border": "1px solid #242424",
        "secondary-button-focus-border-color": "#C7C7C7",
        "secondary-button-text-color": "#E3E3E3",
        "secondary-button-disabled-text-color": "#E3E3E3",
        "primary-button-hover-color": "#0091FF",
        "primary-button-disabled-color": "#4DB2FF",
        "primary-button-border": "1px solid #4DB2FF",
        "primary-button-focus-border-color": "#4DB2FF",
        "primary-button-text-color": "black",
        "primary-button-disabled-text-color": "black",
        "radio-button-border-color": "#E3E3E3",
        "radio-button-checked-background-color": "#E3E3E3",
        "radio-button-hover-border-color": "#4DB2FF",
        "radio-button-hover-background-color": "rgba(227, 227, 227, 0.8)",
        "radio-button-disabled-color": "rgba(227, 227, 227, 0.2)",
        "radio-button-disabled-border-color": "rgba(227, 227, 227, 0.2)",
        "banner-close-button-color": "#E3E3E3"
    },

    highContrast: {
        "close-button-color": "#E3E3E3",
        "secondary-button-disabled-opacity": "0.5",
        "secondary-button-hover-shadow": "none",
        "primary-button-disabled-opacity": "0.5",
        "primary-button-hover-border": "1px solid yellow",
        "primary-button-disabled-border": "1px solid white",
        "primary-button-hover-shadow": "none",
        "banner-background-color": "black",
        "dialog-background-color": "black",
        "primary-button-color": "yellow",
        "text-color": "white",
        "secondary-button-color": "black",
        "secondary-button-disabled-color": "black",
        "secondary-button-border": "1px solid white",
        "background-color-between-page-and-dialog": "rgba(0, 0, 0, 0.6)",
        "dialog-border-color": "yellow",
        "hyperlink-font-color": "yellow",
        "secondary-button-hover-color": "black",
        "secondary-button-hover-border": "1px solid yellow",
        "secondary-button-disabled-border": "1px solid black",
        "secondary-button-focus-border-color": "white",
        "secondary-button-text-color": "white",
        "secondary-button-disabled-text-color": "white",
        "primary-button-hover-color": "#FFFF33",
        "primary-button-disabled-color": "yellow",
        "primary-button-border": "1px solid yellow",
        "primary-button-focus-border-color": "yellow",
        "primary-button-text-color": "black",
        "primary-button-disabled-text-color": "black",
        "radio-button-border-color": "white",
        "radio-button-checked-background-color": "white",
        "radio-button-hover-border-color": "yellow",
        "radio-button-hover-background-color": "rgba(255, 255, 255, 0.8)",
        "radio-button-disabled-color": "rgba(255, 255, 255, 0.2)",
        "radio-button-disabled-border-color": "rgba(255, 255, 255, 0.2)",
        "banner-close-button-color": "#E3E3E3"
    }
    
};
